### ISSUE TITLE
Possible error in mathematical notation

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/dsc-mathematical-notation#1]
The very last summation on the page, the sum (from i = 1 to w) of the products of w(sub)i * x(sub)i.
I think it should be the sum (from i = 1 to length(w)), or sum (from i =1 to abs(w)). This could, however, be a valid notation I'm just not familiar with.

**Comment by Cheffrey2000** [comment]
This issue has been fixed with the following commit: [52751e8](https://github.com/learn-co-curriculum/dsc-mathematical-notation/commit/52751e82f0f9a23542d0d9f63ed4d6a160842844)
